version: '2'

services:
  data:
    image: busybox
    volumes:
      - /vagrant/trisoft/bestvalue/website:/var/www/html
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
      - /tmpfs

  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - app
    volumes_from:
      - data
    ports:
      - "80:80"

  php-fpm:
    container_name: php7-fpm
    build: ./php7-fpm
    image: php7-fpm:local

  app:
    container_name: app
    build: ./app
    volumes_from:
      - data
    working_dir: /var/www/html
    links:
      - mysql
      - redis
      - rabbitmq
      - elasticsearch
      - selenium
      - mailcatcher
      - mongo
    depends_on:
      - php-fpm
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      TERM: "xterm"
      TIMEZONE: "Europe/Bucharest"
      SSH_AUTH_SOCK: /ssh-agent
      VAGRANT: VAGRANT
      APP_CONSOLE_ARGS: --no-debug --env test
    shm_size: 512M
    mem_limit: 2000000000
    extra_hosts:
      - "host:192.168.0.101"

  mysql:
    container_name: mysql
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vagrant

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: tenstartups/redis-commander
    links:
      - redis:redis
    command: --redis-host redis -p 8082
    ports:
      - "8082:8082"

  rabbitmq:
    container_name: rabbitmq
    build: ./rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /

  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    ports:
      - "9200:9200"

  selenium:
    container_name: selenium
    build: ./selenium
    ports:
      - "4444:4444"
    extra_hosts:
    - "bv.test:192.168.2.100"

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  blackfire:
    container_name: blackfire
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: "610b20ee-be22-4e66-addc-e0a6f42ad7ca"
      BLACKFIRE_SERVER_TOKEN: "3f3383de451753b7c3bd232b0d8286eb998173e34bbb6d17fd1ad887ef50499a"

  mongo:
    image: mongo:latest

  mongo-express:
    image: mongo-express:latest
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8081:8081"

