version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ts_bv_website_dev

  web:
    privileged: true
    build: ./apache
    links:
      - mysql
    ports:
      - "80:80"
    volumes:
      - "~/Projects/trisoft/bestvalue/website-sylius-18:/var/www/html"
  #
  # sync:
  #   privileged: true
  #   build: ./sync
  #   command: "/bin/bash /entrypoint.sh"
  #   volumes:
  #     - /var/www/html
  #     - "~/Projects/sandbox/website:/src"
  #   working_dir: /src
