version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    build: ./apache
    links:
      - mysql
    ports:
      - "80:80"
    volumes_from:
      - sync
  sync:
    build: ./sync
    command: "lsyncd -delay 1 -nodaemon -rsync /src /var/www/html"
    volumes:
      - /var/www/html
      - "~/Projects/sandbox/services-play:/src"
    working_dir: /src
    stdin_open: true
    tty: true
